# Generated Makefile -- DO NOT EDIT!

COMPILER_PREFIX=
CXX=C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe
DEPGEN=C:\Users\micha\MagicLeap\mlsdk\v0.18.0\tools\mabu\tools\win\depgen.py
HOST=win64
LD=C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/link.exe
LINKER_PREFIX=
LINKTOUCH=C:/Users/micha/MagicLeap/mlsdk/v0.18.0/tools/mabu/tools/win/linktouch.sh
MLProtoLumin_BASE=C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09
MLProtoLumin_CPPFLAGS=-I$(MLProtoLumin_BASE)/code/inc.gen/ -I$(MLProtoLumin_BASE)/code/inc/ -I$(MLSDK)/include/runtime/app -I$(MLSDK)/include/runtime/core -I$(MLSDK)/include/runtime/external -I$(MLSDK)/include/runtime/uikit -I$(MLSDK)/include/runtime/util -I$(MLSDK)/include/runtime/intergen -I$(MLSDK)/include -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/ATLMFC/include -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/include -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.17134.0/ucrt -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.17134.0/shared -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.17134.0/um -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.17134.0/winrt -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.17134.0/cppwinrt -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/include -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/atlmfc/include -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Auxiliary/VS/include -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/Include/10.0.10240.0/ucrt -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Auxiliary/VS/UnitTest/include
MLProtoLumin_CXXFLAGS=-Gm- -MDd -Od -ZI -GR- -W2 -EHsc -WX
MLProtoLumin_LDFLAGS=/ignore:4099 /nodefaultlib:LIBCMTD -debug:full
MLProtoLumin_LIBS=-libpath:$(MLSDK)/lib/win64/debug -libpath:$(MLSDK)/lib/win64 -libpath:C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/ATLMFC/lib/x64 -libpath:C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/lib/x64 -libpath:C:/Program\ Files\ \(x86\)/Windows\ Kits/10/lib/10.0.17134.0/ucrt/x64 -libpath:C:/Program\ Files\ \(x86\)/Windows\ Kits/10/lib/10.0.17134.0/um/x64 -libpath:C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.14.26428/atlmfc/lib/x64 -libpath:C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Auxiliary/VS/lib/x64 -libpath:C:/Program\ Files\ \(x86\)/Windows\ Kits/10/lib/10.0.10240.0/ucrt/x64 -libpath:C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Auxiliary/VS/UnitTest/lib -libpath:Lib/um/x64 jpeg-static.lib turbojpeg-static.lib lr_core.lib lr_app.lib lr_uikit.lib lr_util.lib lr_renderer.lib lumin_rt_core_1_1.lib lumin_rt_app_1_1.lib lumin_rt_uikit_1_1.lib lumin_rt_util_1_1.lib jsoncpp.lib glfw3.lib mcore.lib emotionfx.lib assimp-vc140-mtd.lib freetyped.lib libpng16_staticd.lib tinyxml2d.lib zlibstaticd.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib ml_remote.lib ml_graphics.lib ml_perception_client.lib ml_input.lib ml_lifecycle.lib ml_ext_logging.lib OpenGL32.lib
MLProtoLumin_OUTPUT=$(MLProtoLumin_BASE)/.out/$(SPEC)
MLSDK=C:/Users/micha/MagicLeap/mlsdk/v0.18.0
PYTHON=C:\Users\micha\MagicLeap\mlsdk\v0.18.0\tools\python3\python.exe
RM=rm
SPEC=debug_win_msvc-2017_x64
srcs_comp_BASE=C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code

$(MLProtoLumin_OUTPUT)/MLProtoLumin.exe : $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Linking\ program\ 'MLProtoLumin.exe'...
	$(ECHO) cd $(MLProtoLumin_OUTPUT) && $(LINKTOUCH) $(MLProtoLumin_OUTPUT)/MLProtoLumin.exe $(LINKER_PREFIX) $(LD) -nologo -out:MLProtoLumin.exe -machine:x64 obj.MLProtoLumin/ButtonHandlers.cpp.o obj.MLProtoLumin/LabelFader.cpp.o obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o obj.MLProtoLumin/code/src/main.cpp.o obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o $(MLProtoLumin_LIBS) $(MLProtoLumin_LDFLAGS)

$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.o : $(MLProtoLumin_BASE)/ButtonHandlers.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'ButtonHandlers.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(MLProtoLumin_BASE)/ButtonHandlers.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(MLProtoLumin_BASE)/ButtonHandlers.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.o : $(MLProtoLumin_BASE)/LabelFader.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'LabelFader.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(MLProtoLumin_BASE)/LabelFader.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(MLProtoLumin_BASE)/LabelFader.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o : $(MLProtoLumin_BASE)/code/src/MLProtoLumin.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'MLProtoLumin.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(MLProtoLumin_BASE)/code/src/MLProtoLumin.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(MLProtoLumin_BASE)/code/src/MLProtoLumin.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.o : $(MLProtoLumin_BASE)/code/src/main.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'main.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(MLProtoLumin_BASE)/code/src/main.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(MLProtoLumin_BASE)/code/src/main.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o : $(srcs_comp_BASE)/src.gen/scenes.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'scenes.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/scenes.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/scenes.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o : $(srcs_comp_BASE)/src.gen/ListsLayoutScene/ListsLayoutScene.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'ListsLayoutScene.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/ListsLayoutScene/ListsLayoutScene.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/ListsLayoutScene/ListsLayoutScene.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'EmergLabel.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'SingleSelectSingleLevelHandlers.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'EmergHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'helpLabelHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/helpList/helpListHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'helpListHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/helpList/helpListHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/helpList/helpListHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'TextWithIconOutlinedButtonHandlers.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'TextWithIconOutlinedLabelHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'washroomButtonHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o : $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'washroomLabelHandler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o : $(srcs_comp_BASE)/src.gen/PrismSceneManager.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'PrismSceneManager.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/PrismSceneManager.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/PrismSceneManager.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o : $(srcs_comp_BASE)/src.gen/SceneDescriptor.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'SceneDescriptor.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/SceneDescriptor.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/SceneDescriptor.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o : $(srcs_comp_BASE)/src.gen/SpawnedSceneBase.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'SpawnedSceneBase.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/SpawnedSceneBase.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/SpawnedSceneBase.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o : $(srcs_comp_BASE)/src.gen/SpawnedSceneHandlers.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'SpawnedSceneHandlers.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/SpawnedSceneHandlers.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/SpawnedSceneHandlers.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.d
$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o : $(srcs_comp_BASE)/src.gen/SpawnedSceneUserData.cpp $(MLProtoLumin_BASE)/MLProtoLumin.mabu C:/Users/micha/Documents/Magic\ Leap/Lumin\ Projects\ Current\ Dec09/code/srcs.comp $(MLSDK)/.metadata/components/lumin_runtime.comp $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[MLProtoLumin\]\ Compiling\ 'SpawnedSceneUserData.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(srcs_comp_BASE)/src.gen/SpawnedSceneUserData.cpp $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o -i $(MLProtoLumin_BASE)/code/inc.gen/ -i $(MLProtoLumin_BASE)/code/inc/ -i $(MLSDK)/include/runtime/app -i $(MLSDK)/include/runtime/core -i $(MLSDK)/include/runtime/external -i $(MLSDK)/include/runtime/uikit -i $(MLSDK)/include/runtime/util -i $(MLSDK)/include/runtime/intergen -i $(MLSDK)/include
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(srcs_comp_BASE)/src.gen/SpawnedSceneUserData.cpp -Fo$(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o -FS -Fd$(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_CPPFLAGS) $(MLProtoLumin_CXXFLAGS)

-include $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.d

MLProtoLumin-prebuild :: 

MLProtoLumin-postbuild :: 

MLProtoLumin-clean :: 
	$(INFO) Cleaning\ MLProtoLumin...
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/MLProtoLumin.exe $(MLProtoLumin_OUTPUT)/MLProtoLumin.ilk $(MLProtoLumin_OUTPUT)/MLProtoLumin.idb $(MLProtoLumin_OUTPUT)/MLProtoLumin.pdb $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/ButtonHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/LabelFader.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/MLProtoLumin.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin/code/src/main.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/scenes.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/ListsLayoutScene/ListsLayoutScene.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/eclipseLabel1/EmergLabel.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/SingleSelectSingleLevelHandlers.cpp.d
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/SSSL_EmergencyList/EmergHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpEclipseLabel/helpLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/helpList/helpListHandler.cpp.d
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/foodEclipseButton/TextWithIconOutlinedButtonHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/BES_Label6/TextWithIconOutlinedLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseBut/washroomButtonHandler.cpp.d
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src/ListsLayoutScene/washroomEclipseLabel/washroomLabelHandler.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/PrismSceneManager.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SceneDescriptor.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneBase.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.o $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneHandlers.cpp.d $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.o
	$(ECHO) $(RM) -rf $(MLProtoLumin_OUTPUT)/obj.MLProtoLumin-srcs/src.gen/SpawnedSceneUserData.cpp.d $(MLProtoLumin_OUTPUT)/lr_resource_locator

MLProtoLumin-all :: -make-directories MLProtoLumin-prebuild $(MLProtoLumin_OUTPUT)/MLProtoLumin.exe MLProtoLumin-postbuild

PROJECT=MLProtoLumin

